"""initial TrendFlow schema"""
from alembic import op
import sqlalchemy as sa
revision="0001_initial"
down_revision=None
branch_labels=None
depends_on=None

def upgrade():
    op.create_table("users",sa.Column("id",sa.String(36),primary_key=True),sa.Column("email",sa.String(255),nullable=False,unique=True),sa.Column("password_hash",sa.String(255),nullable=False),sa.Column("name",sa.String(120),nullable=False,server_default=""),sa.Column("role",sa.String(40),nullable=False,server_default="owner"),sa.Column("created_at",sa.DateTime(),nullable=False))
    op.create_table("workspaces",sa.Column("id",sa.String(36),primary_key=True),sa.Column("owner_id",sa.String(36),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("plan",sa.String(40),nullable=False,server_default="creator"),sa.Column("created_at",sa.DateTime(),nullable=False))
    op.create_table("workspace_members",sa.Column("id",sa.String(36),primary_key=True),sa.Column("workspace_id",sa.String(36),nullable=False),sa.Column("user_id",sa.String(36),nullable=False),sa.Column("role",sa.String(40),nullable=False,server_default="editor"))
    op.create_table("influencers",sa.Column("id",sa.String(36),primary_key=True),sa.Column("name",sa.String(120),nullable=False),sa.Column("dna",sa.JSON(),nullable=False),sa.Column("status",sa.String(40),nullable=False,server_default="active"),sa.Column("created_at",sa.DateTime(),nullable=False))
    op.create_table("assets",sa.Column("id",sa.String(36),primary_key=True),sa.Column("influencer_id",sa.String(36),nullable=False),sa.Column("kind",sa.String(40),nullable=False),sa.Column("uri",sa.Text(),nullable=False),sa.Column("public_url",sa.Text(),nullable=False,server_default=""),sa.Column("metadata",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False))
    op.create_table("content",sa.Column("id",sa.String(36),primary_key=True),sa.Column("influencer_id",sa.String(36),nullable=False),sa.Column("title",sa.String(200),nullable=False),sa.Column("status",sa.String(40),nullable=False,server_default="DRAFT"),sa.Column("payload",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False))
    op.create_table("social_accounts",sa.Column("id",sa.String(36),primary_key=True),sa.Column("influencer_id",sa.String(36),nullable=False),sa.Column("platform",sa.String(40),nullable=False),sa.Column("handle",sa.String(160),nullable=False,server_default=""),sa.Column("connected",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("external_id",sa.String(200),nullable=False,server_default=""),sa.Column("token_ciphertext",sa.Text(),nullable=False,server_default=""),sa.Column("refresh_ciphertext",sa.Text(),nullable=False,server_default=""),sa.Column("expires_at",sa.DateTime(),nullable=True),sa.Column("metadata",sa.JSON(),nullable=False))
    op.create_table("analytics",sa.Column("id",sa.String(36),primary_key=True),sa.Column("content_id",sa.String(36),nullable=False),sa.Column("platform",sa.String(40),nullable=False),sa.Column("metrics",sa.JSON(),nullable=False),sa.Column("captured_at",sa.DateTime(),nullable=False))
    op.create_table("calendar_items",sa.Column("id",sa.String(36),primary_key=True),sa.Column("influencer_id",sa.String(36),nullable=False),sa.Column("content_id",sa.String(36)),sa.Column("platform",sa.String(40),nullable=False),sa.Column("scheduled_at",sa.DateTime(),nullable=False),sa.Column("status",sa.String(40),nullable=False,server_default="scheduled"),sa.Column("notes",sa.Text(),nullable=False,server_default=""))
    op.create_table("brand_deals",sa.Column("id",sa.String(36),primary_key=True),sa.Column("influencer_id",sa.String(36),nullable=False),sa.Column("brand",sa.String(180),nullable=False),sa.Column("contact",sa.String(255),nullable=False,server_default=""),sa.Column("stage",sa.String(50),nullable=False,server_default="lead"),sa.Column("value",sa.Integer(),nullable=False,server_default="0"),sa.Column("brief",sa.Text(),nullable=False,server_default=""),sa.Column("created_at",sa.DateTime(),nullable=False))
    op.create_table("subscriptions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("user_id",sa.String(36),nullable=False),sa.Column("plan",sa.String(40),nullable=False,server_default="starter"),sa.Column("status",sa.String(40),nullable=False,server_default="active"),sa.Column("provider_customer_id",sa.String(160),nullable=False,server_default=""),sa.Column("provider_subscription_id",sa.String(160),nullable=False,server_default=""))
    op.create_table("audit",sa.Column("id",sa.String(36),primary_key=True),sa.Column("event",sa.String(80),nullable=False),sa.Column("entity_id",sa.String(80),nullable=False),sa.Column("details",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False))
    for table,cols in {"workspace_members":[("workspace_id","ix_workspace_members_workspace_id"),("user_id","ix_workspace_members_user_id")],"influencers":[("status","ix_influencers_status")],"assets":[("influencer_id","ix_assets_influencer_id")],"content":[("influencer_id","ix_content_influencer_id"),("status","ix_content_status")],"social_accounts":[("influencer_id","ix_social_accounts_influencer_id"),("platform","ix_social_accounts_platform")],"analytics":[("content_id","ix_analytics_content_id"),("captured_at","ix_analytics_captured_at")],"calendar_items":[("influencer_id","ix_calendar_items_influencer_id"),("scheduled_at","ix_calendar_items_scheduled_at")],"brand_deals":[("influencer_id","ix_brand_deals_influencer_id"),("stage","ix_brand_deals_stage")],"subscriptions":[("user_id","ix_subscriptions_user_id")],"audit":[("event","ix_audit_event"),("created_at","ix_audit_created_at")]}.items():
        for col,idx in cols:op.create_index(idx,table,[col])
def downgrade():
    for t in ["audit","subscriptions","brand_deals","calendar_items","analytics","social_accounts","content","assets","influencers","workspace_members","workspaces","users"]:op.drop_table(t)